service: auctions-aws-service
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  environment:
    AUCTION_TABLE_NAME: ${self:custom.AuctionTable.name}
  iamRoleStatements:
    - ${file(aws_config/iam/AuctionTableIAM.yml):AuctionTableIAM}

functions:
  createAuction:
    handler: src/auctions/createAuction.createAuction
    events:
      - httpApi:
          path: /auctions
          method: POST

  getAuctions:
    handler: src/auctions/getAuctions.getAuctions
    events:
      - httpApi:
          path: /auctions
          method: GET
  
  getAuctionById:
    handler: src/auctions/getAuctionById.getAuctionById
    events:
      - httpApi:
          path: /auctions/{id}
          method: GET

resources:
  Resources:
    AuctionTable: ${file(aws_config/resources/AuctionTable.yml):AuctionTable}

custom:
  AuctionTable:
    name: !Ref AuctionTable
    arn: !GetAtt AuctionTable.Arn
